//! The two icon files the bundle ships.
//!
//! Both are generated by `assets/appicon.sh` and committed, because CI has no
//! SVG renderer and `generate_context!` reads one of them at compile time. CI
//! also never builds a bundle, so without this nothing would notice a
//! regeneration that dropped a layer, lost the Dock margin, or went back to a
//! 1024 square.

#![deny(dead_code, unused_imports, unused_variables, unused_mut)]

use std::path::PathBuf;

fn manifest() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// The layers of an icns, by their four-character type. The container is a
/// magic word, a length, and then a run of type-plus-length blocks.
fn layers(file: &[u8]) -> Vec<(String, &[u8])> {
    assert_eq!(&file[..4], b"icns", "this is not an icns container");

    let mut found = Vec::new();
    let mut at = 8;
    while at + 8 <= file.len() {
        let kind = String::from_utf8_lossy(&file[at..at + 4]).into_owned();
        let length =
            u32::from_be_bytes([file[at + 4], file[at + 5], file[at + 6], file[at + 7]]) as usize;
        assert!(
            length >= 8 && at + length <= file.len(),
            "{kind} runs off the end"
        );
        found.push((kind, &file[at + 8..at + length]));
        at += length;
    }
    found
}

/// The image header of a PNG: width, height and colour type.
fn header(file: &[u8]) -> (u32, u32, u8) {
    assert_eq!(&file[..8], b"\x89PNG\r\n\x1a\n", "this is not a png");
    assert_eq!(
        &file[12..16],
        b"IHDR",
        "the png does not open with its header"
    );

    let number =
        |at: usize| u32::from_be_bytes([file[at], file[at + 1], file[at + 2], file[at + 3]]);
    (number(16), number(20), file[25])
}

/// A regeneration that quietly dropped a size - a renamed iconset file, a future
/// `iconutil` that stopped writing a type. A missing 1024 layer shows up only as
/// a blurry icon on somebody else's Dock.
#[test]
fn the_icns_carries_every_layer_the_bundle_needs() {
    let file = std::fs::read(manifest().join("icons/icon.icns")).expect("the icns is committed");
    let found = layers(&file);

    for wanted in [
        "ic07", "ic08", "ic09", "ic10", "ic11", "ic12", "ic13", "ic14",
    ] {
        let layer = found
            .iter()
            .find(|(kind, _)| kind == wanted)
            .unwrap_or_else(|| panic!("the icns has no {wanted} layer"));
        assert!(!layer.1.is_empty(), "{wanted} is empty");
    }
}

/// Every pixel of the window icon costs four bytes in the shipped binary, and
/// macOS never draws one: a 1024 square would spend four megabytes of a fifteen
/// megabyte budget on nothing. The colour type is here too, because
/// `generate_context!` panics with "is not RGBA" a long way from its cause.
#[test]
fn the_window_icon_is_rgba_and_small_enough_to_embed() {
    let file = std::fs::read(manifest().join("icons/icon.png")).expect("the icon is committed");
    let (width, height, colour) = header(&file);

    assert_eq!(colour, 6, "the window icon is not RGBA");
    assert!(
        width <= 128 && height <= 128,
        "the window icon is {width}x{height}, which is {} bytes of binary",
        width as usize * height as usize * 4
    );
}

/// The defect this slice exists to fix, and the one nothing else would catch: a
/// full-bleed icon passes every other check and simply stands a quarter wider
/// than everything beside it in the Dock, forever.
#[test]
fn the_largest_layer_keeps_the_dock_margin() {
    let file = std::fs::read(manifest().join("icons/icon.icns")).expect("the icns is committed");
    let found = layers(&file);
    let (_, layer) = found
        .iter()
        .find(|(kind, _)| kind == "ic10")
        .expect("the icns has no 1024 layer");

    let mut reader = png::Decoder::new(std::io::Cursor::new(*layer))
        .read_info()
        .expect("the layer is a png");
    let mut pixels = vec![0; reader.output_buffer_size().expect("it states a size")];
    let frame = reader.next_frame(&mut pixels).expect("the layer decodes");

    assert_eq!((frame.width, frame.height), (1024, 1024));
    assert_eq!(frame.color_type, png::ColorType::Rgba);

    // Apple's grid draws on the middle 824, which leaves a hundred pixels of
    // nothing on every side. One pixel of slack for the supersampled edge.
    let margin = (1024 - 824) / 2 - 1;
    let alpha = |x: usize, y: usize| pixels[(y * 1024 + x) * 4 + 3];

    for along in 0..1024 {
        for ring in 0..margin {
            for (x, y) in [
                (along, ring),
                (along, 1023 - ring),
                (ring, along),
                (1023 - ring, along),
            ] {
                assert_eq!(
                    alpha(x, y),
                    0,
                    "the icon is drawn at ({x}, {y}), inside the margin"
                );
            }
        }
    }

    assert_ne!(
        alpha(1024 / 2, margin + 2),
        0,
        "the ground does not reach the margin"
    );
}

/// `find_icon` takes the first `.png` in the list for the compiled-in window
/// icon, so a second one listed silently costs megabytes with no other symptom.
#[test]
fn the_bundle_names_one_png_and_it_is_the_small_one() {
    let configuration: serde_json::Value = serde_json::from_slice(
        &std::fs::read(manifest().join("tauri.conf.json")).expect("the configuration is there"),
    )
    .expect("the configuration parses");

    let listed: Vec<&str> = configuration["bundle"]["icon"]
        .as_array()
        .expect("the bundle names its icons")
        .iter()
        .map(|path| path.as_str().expect("a path is a string"))
        .collect();

    for path in &listed {
        assert!(
            manifest().join(path).is_file(),
            "{path} is named but not there"
        );
    }

    let pngs: Vec<&&str> = listed
        .iter()
        .filter(|path| path.ends_with(".png"))
        .collect();
    assert_eq!(pngs, vec![&"icons/icon.png"]);
    assert!(
        listed.iter().any(|path| path.ends_with(".icns")),
        "the bundle names no icns"
    );
}
